# Generated by Django 5.1.3 on 2024-11-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Haqida')),
                ('rating', models.FloatField(verbose_name='Reyting')),
                ('ratings_count', models.PositiveIntegerField()),
                ('price_from', models.CharField(max_length=50)),
                ('price_to', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('destination', 'Destination'), ('real_estate', 'Real Estate'), ('automotion', 'Automotion')], max_length=50)),
                ('image', models.ImageField(upload_to='', verbose_name='Mehmonxona rasmi')),
                ('person_image', models.ImageField(upload_to='hotel/people/', verbose_name='Odam rasmi')),
                ('person_name', models.CharField(max_length=255)),
                ('is_open', models.BooleanField(default=False, verbose_name='Ochiq yoki yopiq')),
                ('button_label', models.CharField(default='best rated', max_length=50)),
                ('map_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mehmonxona',
                'verbose_name_plural': 'Mehmonxonalar',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
