# Generated by Django 5.1.3 on 2024-11-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploreitem',
            name='price_from',
            field=models.CharField(max_length=50, verbose_name='Narxi'),
        ),
    ]
