# Generated by Django 5.0.7 on 2024-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('listings', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'managed': True, 'verbose_name': 'comment', 'verbose_name_plural': 'coomentt'},
        ),
        migrations.AlterModelTable(
            name='testimonial',
            table='',
        ),
    ]
