# Generated by Django 5.0.7 on 2024-11-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_topic_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='additional_icon',
            field=models.ImageField(blank=True, null=True, upload_to='additional_icons/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
