# Generated by Django 5.1.3 on 2024-11-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hodelserachview_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodelserachview',
            name='search',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.exploreitem'),
            preserve_default=False,
        ),
    ]
