# Generated by Django 5.0.7 on 2024-11-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hodelserachview_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=20)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('google_plus_url', models.URLField(blank=True, help_text='Google Plus profile URL', null=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.DeleteModel(
            name='HodelSerachView',
        ),
    ]
